[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
license = "MIT OR Apache-2.0"
edition = "2024"

[workspace.lints.clippy]
multiple_crate_versions = "allow"

[workspace.dependencies]
ring = "0.17.14"
hex = "0.4.3"
smplx-std = { version = "0.0.10" }
sha2 = { version = "0.10.9", features = ["compress"] }
serde = { version = "1.0.228", features = ["derive"] }
thiserror = { version = "2.0.18" }
tracing = { version = "0.1.41" }
[patch.crates-io.smplx-std]
git = "https://github.com/gerau/smplx.git"
rev = "e27ae4978e14c943e4f1c34d0da320dac5e834a7"
