// This file is @generated by Simplex. Do not edit manually.

#![allow(clippy::all)]
#[rustfmt::skip]
pub mod asset_auth;
#[rustfmt::skip]
pub mod issuance_factory;
#[rustfmt::skip]
pub mod asset_auth_vault;
#[rustfmt::skip]
pub mod script_auth;
#[rustfmt::skip]
pub mod lending;
